Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -172,6 +172,7 @@ jobs:
           
           echo "===== BIBLIOGRAPHY FILES ====="
           find _bibliography -maxdepth 1 -type f -print
+          test -f _bibliography/mypublication.bib && echo "MYPUBLICATION: FOUND" || echo "MYPUBLICATION: NOT FOUND"
           
           echo "===== BUILD ====="
           bundle exec jekyll build
